name: whatidid
description: Diary app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^0.14.0+2

  flutter_svg: ^0.22.0

  flutter_local_notifications: ^5.0.0+1

  sembast: ^3.0.2
  shared_preferences: ^2.0.5

  equatable: ^1.2.5
  dartz: ^0.10.0-nullsafety.1
  

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/empty.svg
    - assets/images/notebook.svg
    - assets/lang/en.json
    - assets/lang/pt.json

  fonts:
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf